CREATE TABLE BOARD(
    BOARD_NO        NUMBER  PRIMARY KEY,
    BOARD_TITLE     VARCHAR2(60) NOT NULL,
    BOARD_CONTENT   VARCHAR2(500) NOT NULL,
    WRITER          VARCHAR2(30) NOT NULL,
    EN_DATE         DATE
);
SELECT * FROM BOARD;
DROP TABLE BOARD;
CREATE SEQUENCE BOARD_SEQ NOCACHE;
DROP SEQUENCE BOARD_SEQ;
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'TEST','³»¿ë¾å','À¯Àú1',SYSDATE);
DELETE FROM BOARD WHERE BOARD_NO = 1;
COMMIT;