CREATE TABLE EXAM_MEMBER(
    MEMBER_NO   NUMBER          PRIMARY KEY,
    MEMBER_ID   VARCHAR2(20)    UNIQUE,
    MEMBER_PW   VARCHAR2(30)    NOT NULL,
    MEMBER_NAME VARCHAR2(20)    NOT NULL,
    PHONE       CHAR(11)
);
SELECT * FROM EXAM_MEMBER;
DELETE FROM EXAM_MEMBER WHERE MEMBER_NO = 3;
CREATE SEQUENCE EXAM_MEMBER_SEQ NOCACHE;
DROP SEQUENCE EXAM_MEMBER_SEQ;
CREATE TABLE EXAM_BOARD(
    BOARD_NO        NUMBER          PRIMARY KEY,
    BOARD_TITLE     VARCHAR2(100)   NOT NULL,
    BOARD_CONTENT   VARCHAR(2000)   NOT NULL,
    BOARD_WRITER    VARCHAR2(20)    REFERENCES EXAM_MEMBER(MEMBER_ID) ON DELETE SET NULL,
    READ_COUNT      NUMBER          DEFAULT 0,
    WRITE_DATE      DATE            DEFAULT SYSDATE
);
SELECT * FROM EXAM_BOARD;
CREATE SEQUENCE EXAM_BOARD_SEQ NOCACHE;
COMMIT;

SELECT board_no,board_title,MEMBER_NAME,read_count,write_date FROM exam_board
join exam_member on (member_id = board_writer);
                