CREATE TABLE PHOTO(
    PHOTO_NO        NUMBER          PRIMARY KEY,
    PHOTO_WRITER    VARCHAR2(20)    REFERENCES MEMBER(MEMBER_ID),
    PHOTO_CONTENT   VARCHAR2(1000)  NOT NULL,
    FILEPATH        VARCHAR2(300),
    PHOTO_DATE      CHAR(10)
);

CREATE SEQUENCE PHOTO_SEQ;

SELECT * FROM PHOTO;